### ISSUE TITLE
Hive checklist edit unable to edit category order

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#20]
There needs to be a means to change the order of the hive checklist categories. Maybe in the select tree, but may also be in the checklist itself (as an edit mode)

**Comment by JuliaBD** [comment]
@pvgennip On desktop, changing the order by dragging and dropping is enabled. On mobile, it doesn't seem to work indeed.

This is a Tree element from element-ui. For the 'draggable' example on the element-ui website itself, drag- and dropping doesn't seem to work for mobile either, see https://element.eleme.io/#/en-US/component/tree#draggable...

Since it seems to be inherent to the component, I think there are 2 options:
1. try a different type of tree element / build one ourselves
2. change the description text for mobile, refer to desktop for changing the order

Depends on how much time we have left / the importance of this issue.

**Comment by pvgennip** [comment]
@JuliaBD Ok, let's go for the desktop only option and tell that in the description.
